{
 "title": "Luxor Miner",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pool", "label": "Pool", "query": "luxor" },
   { "name": "subaccount", "label": "Subaccount", "query": { "query": "luxor_miner_last_seen_seconds" } },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "15m,30m,1h,3h,6h,12h,1d,1w,1m" }
  ]
 },
 "panels": [
  {
   "title": "Active Workers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxor_miner_workers_active{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}"
    }
   ]
  },
  {
   "title": "Valid Shares",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxor_miner_shares_valid{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"} / (luxor_miner_shares_valid{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"} + luxor_miner_shares_invalid{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"} + luxor_miner_shares_stale{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"})",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Average Hash Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Hs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxor_miner_hashrate_average_hps{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Income (Daily)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxor_miner_income_minute_usd{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"} * 60 * 24",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Income (Yearly)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxor_miner_income_minute_usd{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"} * 60 * 24 * 365",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Unpaid Balance",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "luxor_miner_balance_unpaid_usd{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}",
     "legendFormat": "Current"
    }
   ]
  },
  {
   "title": "Hash Rates [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_miner_hashrate_current_hps{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Current"
    },
    {
     "expr": "avg_over_time(luxor_miner_hashrate_average_hps{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Shares [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_miner_shares_valid{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Valid"
    },
    {
     "expr": "avg_over_time(luxor_miner_shares_invalid{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Invalid"
    },
    {
     "expr": "avg_over_time(luxor_miner_shares_stale{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Stale"
    }
   ]
  },
  {
   "title": "Income (Coins) (Daily) [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_miner_income_minute_coins{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval]) * 60 * 24",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Income (USD) (Daily) [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_miner_income_minute_usd{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval]) * 60 * 24",
     "legendFormat": "Value"
    }
   ]
  },
  {
   "title": "Unpaid Coins [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_miner_balance_unpaid_coins{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Ethereum value"
    }
   ]
  },
  {
   "title": "Worker Count [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_miner_workers_active{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "Miner"
    }
   ]
  },
  {
   "title": "Worker Hash Rates [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "Hs" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_worker_hashrate_current_hps{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{worker}} (current)"
    }
   ]
  },
  {
   "title": "Worker Shares [$smoothing_interval]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg_over_time(luxor_worker_shares_valid{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{worker}} (valid)"
    },
    {
     "expr": "avg_over_time(luxor_worker_shares_invalid{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{worker}} (invalid)"
    },
    {
     "expr": "avg_over_time(luxor_worker_shares_stale{pool=~\"${pool:pipe}\", subaccount=~\"${subaccount:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{worker}} (stale)"
    }
   ]
  }
 ]
}