global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: luxor-selfmining
    # Limit due to API rate restriction
    scrape_interval: 15m
    scrape_timeout: 5m
    metrics_path: /miner
    params:
      pool: [luxor]
      apikey: [key] # Modify this with the proper apike
      subaccount: [subaccount] # Modify this with the proper subaccount
    static_configs:
      - targets:
          - F6403152cAd46F2224046C9B9F523d690E41Bffd
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:8080
